name: Scholar Sync

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml scholarly

      - name: Run sync
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          python scripts/scholar_sync.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: chore: sync publications from Google Scholar
          title: chore: sync publications from Google Scholar
          body: |
            Automated update of publications from Google Scholar.
          branch: scholar-sync/update
          delete-branch: true
          add-paths: |
            _publications/auto/*.md 